"""empty message

Revision ID: 16ac8c56f29c
Revises: 1727bc06f1a6
Create Date: 2021-06-19 13:59:49.844277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ac8c56f29c'
down_revision = '1727bc06f1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', sa.String(length=24), nullable=True))
    op.add_column('student', sa.Column('contact', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'student', ['contact'])
    op.create_unique_constraint(None, 'student', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    # ### end Alembic commands ###
