"""empty message

Revision ID: 532f79b344ba
Revises: 57f7604d0c8c
Create Date: 2021-06-19 15:48:16.300051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532f79b344ba'
down_revision = '57f7604d0c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_admin_username'), ['username'])

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_grade_grade_number'), ['grade_number'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_staff_contact'), ['contact'])
        batch_op.create_unique_constraint(batch_op.f('uq_staff_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_staff_username'), ['username'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=24), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_student_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_username'), type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('address')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_staff_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_staff_contact'), type_='unique')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_grade_grade_number'), type_='unique')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_admin_username'), type_='unique')

    # ### end Alembic commands ###
