"""empty message

Revision ID: 583812599fc0
Revises: 
Create Date: 2021-05-24 17:32:32.365329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583812599fc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=24), nullable=True),
    sa.Column('last_name', sa.String(length=24), nullable=True),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('address', sa.Text(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_first_name'), 'admin', ['first_name'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_number', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_number'),
    sa.UniqueConstraint('grade_number')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=24), nullable=True),
    sa.Column('middle_name', sa.String(length=24), nullable=True),
    sa.Column('last_name', sa.String(length=24), nullable=True),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('gender', sa.String(length=12), nullable=True),
    sa.Column('address', sa.Text(length=100), nullable=True),
    sa.Column('email', sa.String(length=24), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('seson_start_year', sa.DateTime(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_staff_first_name'), 'staff', ['first_name'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=24), nullable=True),
    sa.Column('middle_name', sa.String(length=24), nullable=True),
    sa.Column('last_name', sa.String(length=24), nullable=True),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('gender', sa.String(length=12), nullable=True),
    sa.Column('address', sa.Text(length=100), nullable=True),
    sa.Column('seson_start_year', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_student_first_name'), 'student', ['first_name'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('market_value', sa.Integer(), nullable=True),
    sa.Column('publisher_name', sa.String(length=36), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_student_first_name'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_staff_first_name'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('grade')
    op.drop_index(op.f('ix_admin_first_name'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
