"""empty message

Revision ID: 7afd45f040cd
Revises: 16ac8c56f29c
Create Date: 2021-06-19 14:34:59.793653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afd45f040cd'
down_revision = '16ac8c56f29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint(None, 'student', ['contact'])
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    # ### end Alembic commands ###
