"""grades table

Revision ID: 879492fffc61
Revises: 583812599fc0
Create Date: 2021-05-24 19:42:48.127043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879492fffc61'
down_revision = '583812599fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('total_subject', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade', 'total_subject')
    # ### end Alembic commands ###
